### ISSUE TITLE
How to improve page

### ISSUE THREAD

**Issue by gptix** [Lisp-Stat/documentation#11]
Add content

**Comment by snunez1** [comment]
Thanks for the feedback. Which page in particular needs content added?

**Comment by gptix** [comment]
Owe.

I'll go back through. I expected the tool taking feedback to note the page from which it was launched.

The Atlanta Functional Programming Meetup (remote meetings via Youtube and Jitsi) is going to show off LispStat.

I want to show how to use Lisp (functional, compiled, macros) to magnify the power of programmers.

Thanks for the valuable work!

Jud

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by snunez1** [comment]
That's great! Let me know how I can help.

**Comment by snunez1** [comment]
Closing, as the page which needs improvement isn't specified.
