### ISSUE TITLE
System "ips" not found in Quicklisp

### ISSUE THREAD

**Issue by lukego** [Lisp-Stat/documentation#4]
The Documentation example at https://lisp-stat.dev/docs/tasks/plotting/ suggests running

```lisp
(ql:quickload :ips)
```

but this doesn't work because the "ips" package is not included in the current Quicklisp distribution.

**Comment by snunez1** [comment]
I've fixed this locally. The documentation is currently a WIP as I update for the new data frame; this fix will come out with the new doc set. Thanks for reporting it.

IPS itself will need updating too, as the API has changed a bit.

**Comment by snunez1** [comment]
Fixed in 43de1cb
